apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.integration.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.integration.name }}
spec:
  type: {{ .Values.integration.service.type }}
  ports:
    - port: {{ .Values.integration.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.integration.name }}
