apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inventory.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.inventory.name }}
spec:
  type: {{ .Values.inventory.service.type }}
  ports:
    - port: {{ .Values.inventory.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.inventory.name }}
