{{- if .Values.support.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.support.name }}
  labels:
    app: {{ .Values.support.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.support.name }}
  minReplicas: {{ .Values.support.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.support.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.support.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.support.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.support.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.support.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
